"""Added User

Revision ID: 94a9ce170d19
Revises: d47901b15b6b
Create Date: 2023-10-18 21:54:38.070697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94a9ce170d19'
down_revision: Union[str, None] = 'd47901b15b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['author_id'], ['id'])
    op.drop_column('message', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'author_id')
    op.add_column('message', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('user')
    # ### end Alembic commands ###
